# Generated by Django 2.0 on 2020-09-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingtable',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
