# Generated by Django 2.0 on 2020-09-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200910_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingtable',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
